name: Build .NET Project on Windows

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Check out the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '4.0'  # Specify the .NET version (use the version your project needs)

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore 2dxrender/2dxrender.csproj

      # Build the project
      - name: Build project
        run: dotnet build 2dxrender/2dxrender.csproj --configuration Release

      # Publish to create an .exe file
      - name: Publish project
        run: dotnet publish 2dxrender/2dxrender.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true

      # Upload the .exe artifact (optional)
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-application
          path: 2dxrender/bin/Release/net7.0/win-x64/  # This is the path to the published .exe file (usually bin/Release/netX/win-x64)
